language: java
jdk:
- oraclejdk8
script: mvn clean package -Dmaven.test.skip=true
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.m2/repository
notifications:
  email:
  - thomas_li@aliyun.com
deploy:
  provider: releases
  api_key:
    secure: b7ThQj+bBPFeyfOG0IEN6z3dSlmtrlMrf5aicNkI5Dud03VkZlfagKkzfiAtn61BuZe1Aiiv3SXig9YXmE79ONLfcZJ4ydMA5CP/tI97LRooEx2e3ocV/fISO4NlDPuwwUgHZRLa426qDQmi09NhWLRUy0VeWVmVPEZ0eRu7/IWla4GB19QIqgJx/oqaBpVhDmpfGpp7YKN0omKKK8bSzWhJRwqJpINHYCgaEQQYbVMoGW1eTQbBdh3XOGbTowmcCN7eqmJnLK282e9rSeWpmjpt3Uh6iXBI9u4y+ZRyFX0ZsJIRzBSdapug14JKOU94Yimf7w5Lzay3vLfmj7IZhhlJl3Jy05dvJ53ozStCie21HER7zcVUsQbxOgReVLbXMprhocL0GKFPtR8fCXAPE8UEhi6RrqPHnuHgVWPXD3mrIEcKwqT9gCSbtkuBlWdVHWFGRUNY70Yq7Imssk2WGNyqVnx4az9JLVC5pouvQrXV++5Hz+vxsfnl9rnpgQftzs2vUV54OGAWVyMvicO7Iz7I/VZAniuurKdlEebgDhkyJ9JaleXgE1LYh2zHiihXbZUPIbOpNEWcqaHJfrTMI7dHF7iZJvD1VKvePwmknRUxMzA6xk1guPlC6J1zZmIOPGmPN2uoADiMuNcFUuB5q5pH6mU1PyKzLpYOmhFH3tk=
  file: /home/travis/build/thomas-li-67/weixin-java-tools/weixin-java-open/target/weixin-java-open-2.9.0.jar
  skip_cleanup: true
  on:
    repo: thomas-li-67/weixin-java-tools
